server:
  port: 8888

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.89:3306/test_zh?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: vzp-admin
    password: jZoq9Tl2OzP48Z1V
#mybatis:
#  mapper-locations: classpath:generator/*.xml
logging:
  level:
    com.zh.boot.launch: debug
mybatis-plus:
  global-config:
    db-config:
      table-prefix: boot_ #表前缀